version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: metrics_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: metrics_dashboard
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SSL: false
      FRONTEND_URL: http://localhost:3000
      LOG_LEVEL: debug
      JIRA_BASE_URL: ${JIRA_BASE_URL:-}
      JIRA_EMAIL: ${JIRA_EMAIL:-}
      JIRA_API_TOKEN: ${JIRA_API_TOKEN:-}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_logs:/app/logs
    networks:
      - app-network

  # Frontend Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  backend_logs:
    driver: local

networks:
  app-network:
    driver: bridge
