apiVersion: v1
kind: Namespace
metadata:
  name: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes
    environment: production
  annotations:
    description: "Metrics Dashboard application namespace"
    contact: "platform-team@company.com"
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: metrics-dashboard-quota
  namespace: metrics-dashboard
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
    persistentvolumeclaims: "5"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
# Network Policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metrics-dashboard-network-policy
  namespace: metrics-dashboard
spec:
  podSelector:
    matchLabels:
      app: metrics-dashboard
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: metrics-dashboard
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 3001
  egress:
  - to: []  # Allow all egress (can be restricted as needed)
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: UDP
      port: 53   # DNS
