apiVersion: v1
kind: Secret
metadata:
  name: metrics-dashboard-secrets
  namespace: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Note: In production, these should be populated from Azure Key Vault
  # using the Secret Store CSI Driver or External Secrets Operator
  DB_PASSWORD: ""  # Base64 encoded password from Key Vault
  JWT_SECRET: ""   # Base64 encoded JWT secret from Key Vault
  JIRA_API_TOKEN: ""  # Base64 encoded Jira API token from Key Vault

---
# Azure Key Vault Secret Provider Class
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: metrics-dashboard-secrets-provider
  namespace: metrics-dashboard
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""  # Will be populated with Managed Identity Client ID
    keyvaultName: "metrics-kv"  # Your Azure Key Vault name
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: jira-api-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: jira-email
          objectType: secret
          objectVersion: ""
        - |
          objectName: jira-base-url
          objectType: secret
          objectVersion: ""
    tenantId: ""  # Your Azure Tenant ID
  secretObjects:
  - data:
    - key: DB_PASSWORD
      objectName: db-password
    - key: JWT_SECRET
      objectName: jwt-secret
    - key: JIRA_API_TOKEN
      objectName: jira-api-token
    - key: JIRA_EMAIL
      objectName: jira-email
    - key: JIRA_BASE_URL
      objectName: jira-base-url
    secretName: metrics-dashboard-secrets
    type: Opaque

---
# Service Account with Azure Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-dashboard-sa
  namespace: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
  annotations:
    azure.workload.identity/client-id: ""  # Azure Managed Identity Client ID
    azure.workload.identity/tenant-id: ""  # Azure Tenant ID
automountServiceAccountToken: true
