apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-dashboard-logs
  namespace: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi  # Azure Disk CSI driver
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: logs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-dashboard-tmp
  namespace: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: temporary

---
# Optional: Azure Files for shared storage (if needed)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-dashboard-shared
  namespace: metrics-dashboard
  labels:
    app.kubernetes.io/name: metrics-dashboard
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi  # Azure Files CSI driver
  resources:
    requests:
      storage: 5Gi
